org: crits
app: helloworld
service: markdownlandingpage

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  cfnRole: arn:aws:iam::770422195241:role/SFProRole-cgradwohl

functions:
  graphql:
    handler: dist/graphql.handler
    events:
      - http:
          path: graphql
          method: GET
          cors: true
      - http:
          path: graphql
          method: POST
          cors: true
